disable_tg_bot = false
debug_mode = false
sqlite_file = "rating.sqlite"
host = "localhost"
port = 3000

[auth]
token = "generate secret"
expiration = "5m"
root_password = "default password"
password_pepper = "generate random string"
sqlite_file = "auth.sqlite"
roles = ["admin", "user"]