disable_tg_bot = false
debug_mode = false
sqlite_file = "rating.sqlite"

[auth]
token = "generate secret"
expiration = "5m"
root_password = "default password"
sqlite_file = "auth.sqlite"
roles = ["admin", "user"]