version: "3.3"

services:
  server:
    build:
      context: ./
      dockerfile: "Dockerfile"
    container_name: server
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - ./rating.sqlite:/app/server/rating.sqlite
      - ./views:/app/server/views

