name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: chromedp/headless-shell:stable
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y \
            build-essential \
            make \
            libnspr4 \
            libnss3 \
            libexpat1 \
            libfontconfig1 \
            libuuid1
      - name: Build bin
        run: make build

      - name: Run tests
        run: make test

      - name: Run auto-tests
        run: make auto-test