name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version-file: go.mod
        cache-dependency-path: go.sum

    - name: Build
      run: make build

    - name: Test
      run: make test

  test:
    runs-on: ubuntu-latest
    container:
      image: chromedp/headless-shell
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod
          cache-dependency-path: go.sum
      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y \
            make \
            chromium \
            libglib2.0-0 \
            libnss3 \
            libx11-xcb1 \
            libxcomposite1 \
            libxdamage1 \
            libxi6 \
            libxtst6 \
            fonts-liberation \
            libasound2 \
            libatk-bridge2.0-0 \
            libgtk-3-0
          
      - name: Build bin
        run: make build

      - name: Run tests
        run: make auto-test